print("TO FIND MAXIMUM AMONG GIVEN NUMBERS")
a=int(input("enter first number"))
b=int(input("enter second number"))
c=int(input("enter third number"))
max=max(a,b,c)
print("maximum among numbers",max)